#!/bin/bash

#find . -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp \
git --no-pager diff --name-only HEAD master | grep ".\.c$\|.\.h$" \
    | xargs clang-format -style=file -output-replacements-xml > clang_format.xml

#git diff > clang_format.patch

# Delete if 0 size and exit with 0
if [ ! -s clang_format.xml ]
then
    rm clang_format.xml
    exit 0
fi

# There were lint issues and should exit with error
exit 1
