node {
  def res = 'SUCCESS'
    withEnv(["UNITY_ROOT=$HOME/Unity", "TOOLCHAIN=$HOME/gcc-arm-none-eabi", "OCWARE_DIR=./"]) {
      try {
          stage('Checkout') {
            step([$class: 'WsCleanup'])
            echo 'Checking out SCM'
            checkout scm
          }
      } catch (err) {
          currentBuild.result = 'FAILURE'
          throw err
      }

      try {
          stage('Static Analysis') {
              sh 'bash .ci/clang_patch'
          }
      } catch (err) {
          res = 'ERROR'
          archiveArtifact artifacts: './clang-format.patch', fingerprint: true
      }
            
      try {
          stage('Unit Test') {
              dir ("firmware/ec/test"){ sh 'make ci' }
          }
      } catch (err) {
          res = 'FAILURE'
      }
          
      try {
          stage('Firmware Build') {
            dir ('firmware/ec') { sh 'make clean all' }
          }
      } catch (err) {
        res = 'FAILURE'
      }
    }
    post {
        always {
            currentBuild.result = res
        }
    }
}
